### ISSUE TITLE
GraphQLGeneratorProvider need filesystem instead of Application ?

### ISSUE THREAD

**Issue by HpiGuillaume** [dalnix/laravel-graphql-generator#1]
Hello,

First: thanks ! Your package seems the solution for me to maintain my heavy project :)

So the issue appear when I try to add the package to composer.

```
$ composer require dalnix/laravel-graphql-generator
Using version ^0.1.0 for dalnix/laravel-graphql-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing dalnix/laravel-graphql-generator (v0.1): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In GraphQLGeneratorProvider.php line 12:

  Argument 1 passed to Dalnix\GraphQLGenerator\GraphQLGeneratorProvider::__co
  nstruct() must be an instance of Illuminate\Filesystem\Filesystem, instance
   of Illuminate\Foundation\Application given, called in /app/vendor/laravel/
  framework/src/Illuminate/Foundation/ProviderRepository.php on line 208


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

Have you already seen that ?

**Comment by slaxxarn** [comment]
I haven't seen that, but will look into it! Thanks for submitting the issue!

**Comment by slaxxarn** [comment]
Need to adjust for latest laravel, i havent tested it for 5.7 yet and you might be running 5.7, right?

**Comment by HpiGuillaume** [comment]
Yes I run for Laravel 5.7 because is the requirement of `folklore/graphql`

**Comment by slaxxarn** [comment]
@HpiGuillaume will you please try dev-master branch or tag 0.2.0 to see if this fix the issue?

**Comment by HpiGuillaume** [comment]
Yes ! I'll make a return in the day

**Comment by HpiGuillaume** [comment]
One things until the package is installing,
Your depends about `folklore/graphql` is on an out dated version (1.0.0) the last stable is 1.10.0
And in this last `folklore/graphql` version there is a depends on `webonyx/graphql-php` version `0.10.2` instead of `0.7`

**Comment by HpiGuillaume** [comment]
```
$ php artisan package:discover -vvv

In Container.php line 767:

  Class graphql does not exist

```

**Comment by slaxxarn** [comment]
For some reason i had to add foklore/graphql's service provider and alias in app.php, try that and if it works i will try to find a more permanent solution.

Regarding different dependencies, i will change them!

**Comment by HpiGuillaume** [comment]
Hello,

I've one error after create my first Query based on Type User on the model User (by default in Laravel)
Seems you pre-shot an error but I don't know how to fix it:
`return Type::listOf(GraphQL::type('UserType')); //If error put: UserType`

I've tried many ways to fix it but nothing works. I've you experimented the same issue in your tests?

**Comment by slaxxarn** [comment]
@HpiGuillaume seems like folklore/laravel-graphql had changed how you should add types via facade, fixed in 0.2.1 and dev-master atleast it worked for me in my tests

**Comment by HpiGuillaume** [comment]
Nice ! Works for me :D

**Comment by HpiGuillaume** [comment]
Thanks for your support !!!

**Comment by slaxxarn** [comment]
No problems glad I could help and thanks for using this package :)
